### ISSUE TITLE
exclude hot-reload code from build

### ISSUE THREAD

**Issue by josdejong** [dat2/react-dev-server#5]
Thanks for this tool, it's really handy!

I noticed that when I build my code like `react-dev-server --build`, the bundle still contains code related to webpack hot reloading. Would be nice if this code could be excluded from the build.

**Comment by dat2** [comment]
Thanks for noticing that bug and opening this issue 👍

**Comment by dat2** [comment]
I've updated the package on npm to include this fix.

**Comment by josdejong** [comment]
wow, that's fast. Thanks!

I was testing your dev server with `preact`, which works right out of the box :). `preact` itself is very small, that's why I noticed the hot-reload code in the bundle.

Here a `preact` example:

``` js
// Tell Babel to transform JSX into h() calls:
/** @jsx h */
import { h, render } from 'preact';

render((
    <div id="foo">
        <span>Hello, world!</span>
        <button onClick={ e => alert("hi!") }>Click Me</button>
    </div>
), document.body);
```

**Comment by dat2** [comment]
I've seen preact before, glad to know it works straight out of the box.

If you don't want to have to put the pragma for jsx everywhere, you may be able to add the Babelrc config here https://babeljs.io/docs/plugins/transform-react-jsx/ although I haven't tried them myself. If you decide to try it let me know :)

**Comment by josdejong** [comment]
I validated whether it also works with .babelrc, it does but requires some work. First you have to install a babel plugin:

```
npm install --save-dev babel-plugin-transform-react-jsx
```

then create a file `.babelrc`:

``` js
{
  "plugins": [
    ["transform-react-jsx", { "pragma": "h"}] // transform using preact
  ]
}
```

**Comment by dat2** [comment]
Yup, I knew you had to install that and create the `.babelrc`. This package handles the `.babelrc` for you, but also allows you to customise your `.babelrc`. Thanks for testing a bit there for me 👍
